window.SITE_CONTENT = window.SITE_CONTENT || {};

(function () {
  function diagram(caption, svg) {
    return '<figure class="diagram ccar-diagram">' + svg + '<figcaption>' + caption + '</figcaption></figure>';
  }

  function visual(kind) {
    var visuals = {
      loop: diagram('The loop is controlled by the API stop reason, with tool results appended before the next model turn.', '<svg viewBox="0 0 680 185" role="img" aria-label="agentic loop"><rect class="node active" x="45" y="64" width="120" height="48" rx="6"/><text x="105" y="93" text-anchor="middle">Claude</text><path class="arrow" d="M 170 88 H 270"/><rect class="node" x="280" y="64" width="120" height="48" rx="6"/><text x="340" y="93" text-anchor="middle">tool_use?</text><path class="arrow" d="M 405 88 H 505"/><rect class="node" x="515" y="64" width="120" height="48" rx="6"/><text x="575" y="93" text-anchor="middle">tool result</text><path class="arrow" d="M 575 120 C 575 165 105 165 105 120"/><text class="label" x="455" y="50">yes → continue</text><text class="muted" x="340" y="174" text-anchor="middle">end_turn → terminate</text></svg>'),
      hub: diagram('Independent specialists receive only the task context the coordinator passes to them; the coordinator owns synthesis.', '<svg viewBox="0 0 680 190" role="img" aria-label="hub and spoke orchestration"><circle class="node active" cx="340" cy="95" r="46"/><text x="340" y="100" text-anchor="middle">coordinator</text><rect class="node" x="65" y="28" width="135" height="44" rx="6"/><rect class="node" x="480" y="28" width="135" height="44" rx="6"/><rect class="node" x="65" y="128" width="135" height="44" rx="6"/><rect class="node" x="480" y="128" width="135" height="44" rx="6"/><text x="132" y="55" text-anchor="middle">research</text><text x="547" y="55" text-anchor="middle">analysis</text><text x="132" y="155" text-anchor="middle">review</text><text x="547" y="155" text-anchor="middle">integration</text><line class="edge" x1="200" y1="58" x2="296" y2="82"/><line class="edge" x1="480" y1="58" x2="384" y2="82"/><line class="edge" x1="200" y1="145" x2="296" y2="109"/><line class="edge" x1="480" y1="145" x2="384" y2="109"/></svg>'),
      gate: diagram('Prompts guide model behavior. A programmatic gate is the control that can actually prevent a prohibited action.', '<svg viewBox="0 0 680 180" role="img" aria-label="programmatic gate"><rect class="node" x="45" y="62" width="125" height="48" rx="6"/><text x="108" y="91" text-anchor="middle">agent request</text><path class="arrow" d="M 175 86 H 280"/><rect class="node active" x="290" y="52" width="130" height="68" rx="6"/><text x="355" y="81" text-anchor="middle">policy gate</text><text class="muted" x="355" y="102" text-anchor="middle">allow / block</text><path class="arrow" d="M 425 86 H 525"/><rect class="node" x="535" y="62" width="105" height="48" rx="6"/><text x="587" y="91" text-anchor="middle">tool</text><text class="label" x="290" y="35">deterministic</text></svg>'),
      tool: diagram('The description and schema narrow the set of requests for which a tool is the obvious choice.', '<svg viewBox="0 0 680 180" role="img" aria-label="tool interface"><rect class="node active" x="40" y="44" width="180" height="90" rx="6"/><text x="130" y="70" text-anchor="middle">tool description</text><text class="muted" x="130" y="93" text-anchor="middle">purpose · boundaries</text><text class="muted" x="130" y="114" text-anchor="middle">examples · edge cases</text><path class="arrow" d="M 225 89 H 330"/><rect class="node" x="340" y="44" width="130" height="90" rx="6"/><text x="405" y="74" text-anchor="middle">schema</text><text class="muted" x="405" y="99" text-anchor="middle">typed input</text><path class="arrow" d="M 475 89 H 570"/><rect class="node" x="580" y="62" width="70" height="54" rx="6"/><text x="615" y="94" text-anchor="middle">call</text></svg>'),
      config: diagram('Configuration is layered: shared project instructions are committed, personal instructions and credentials remain local.', '<svg viewBox="0 0 680 185" role="img" aria-label="Claude Code configuration hierarchy"><rect class="node active" x="60" y="36" width="180" height="44" rx="6"/><text x="150" y="63" text-anchor="middle">project CLAUDE.md</text><rect class="node" x="250" y="36" width="180" height="44" rx="6"/><text x="340" y="63" text-anchor="middle">.mcp.json</text><rect class="node" x="440" y="36" width="180" height="44" rx="6"/><text x="530" y="63" text-anchor="middle">.claude/ skills</text><path class="edge" d="M 150 86 V 128 H 530 V 86"/><rect class="node" x="225" y="136" width="230" height="34" rx="6"/><text x="340" y="158" text-anchor="middle">repository workflow</text><text class="muted" x="340" y="23" text-anchor="middle">version-controlled and shared</text></svg>'),
      prompt: diagram('A schema gives the output a contract; validation tells the system whether to retry, correct, or escalate.', '<svg viewBox="0 0 680 180" role="img" aria-label="structured output validation"><rect class="node" x="45" y="62" width="125" height="48" rx="6"/><text x="108" y="91" text-anchor="middle">prompt</text><path class="arrow" d="M 175 86 H 270"/><rect class="node active" x="280" y="62" width="120" height="48" rx="6"/><text x="340" y="91" text-anchor="middle">JSON output</text><path class="arrow" d="M 405 86 H 500"/><rect class="node" x="510" y="62" width="125" height="48" rx="6"/><text x="572" y="91" text-anchor="middle">validate</text><path class="arrow" d="M 572 118 C 572 160 340 160 340 120"/><text class="label" x="440" y="151">invalid → targeted retry</text></svg>'),
      context: diagram('Reliable systems select, compress, and attribute context rather than placing the whole corpus into every call.', '<svg viewBox="0 0 680 180" role="img" aria-label="context management"><rect class="node" x="40" y="62" width="120" height="48" rx="6"/><text x="100" y="91" text-anchor="middle">sources</text><path class="arrow" d="M 165 86 H 260"/><rect class="node active" x="270" y="52" width="140" height="68" rx="6"/><text x="340" y="80" text-anchor="middle">select + summarize</text><text class="muted" x="340" y="102" text-anchor="middle">retain provenance</text><path class="arrow" d="M 415 86 H 510"/><rect class="node" x="520" y="62" width="120" height="48" rx="6"/><text x="580" y="91" text-anchor="middle">agent turn</text></svg>'),
      drill: diagram('Read the scenario for its constraint, then choose the smallest architecture that provides the required guarantee.', '<svg viewBox="0 0 680 180" role="img" aria-label="exam decision flow"><rect class="node" x="42" y="62" width="135" height="48" rx="6"/><text x="110" y="91" text-anchor="middle">scenario cue</text><path class="arrow" d="M 182 86 H 278"/><rect class="node active" x="288" y="52" width="125" height="68" rx="6"/><text x="350" y="80" text-anchor="middle">required</text><text x="350" y="102" text-anchor="middle">guarantee</text><path class="arrow" d="M 418 86 H 514"/><rect class="node" x="524" y="62" width="115" height="48" rx="6"/><text x="581" y="91" text-anchor="middle">best design</text></svg>')
    };
    return visuals[kind] || visuals.drill;
  }

  function lesson(id, title, problem, choice, boundary, signal, kind, example) {
    var body = '<div class="beat problem"><span class="label">Scenario</span><p>' + problem + '</p></div>';
    body += '<div class="beat solution"><span class="label">Architecture choice</span><p>' + choice + '</p>';
    if (example) body += '<pre><code>' + example.replace(/&/g, '&amp;').replace(/</g, '&lt;') + '</code></pre>';
    body += '</div>' + visual(kind);
    body += '<div class="beat limitation"><span class="label">Boundary</span><p>' + boundary + '</p></div>';
    body += '<div class="gotcha"><span class="label">Exam signal</span><p>' + signal + '</p></div>';
    return { id: id, title: title, body: body };
  }
  function questionSet(id, title, questions) {
    var body = visual('drill') + '<div class="question-set">';
    questions.forEach(function (q, index) {
      body += '<section class="question-card"><span class="question-number">Question ' + (index + 1) + '</span><h2>' + q.prompt + '</h2><ol type="A">' + q.options.map(function (option) { return '<li>' + option + '</li>'; }).join('') + '</ol><details><summary>Show answer</summary><p><strong>' + q.answer + '.</strong> ' + q.reason + '</p></details></section>';
    });
    body += '</div><div class="gotcha"><span class="label">Practice method</span><p>Choose an answer before revealing it. Then name the requirement in the scenario that rules out the tempting alternatives.</p></div>';
    return { id: id, title: title, body: body };
  }
  function track(name, steps) { return { track: name, steps: steps }; }

  window.SITE_CONTENT.architecture = track('1. Agentic Architecture & Orchestration — 27%', [
    lesson('agentic-loop', 'Agentic Loops', 'Claude may request several tools before it can finish a task. A controller needs to know whether to execute a tool, keep the loop alive, or return the final answer.', 'Drive the loop from the API stop reason. Execute every requested tool call, append its tool result to history, and call the model again when the stop reason is tool_use. End on end_turn, with an iteration cap only as a safety fallback.', 'A fixed cap does not make a loop correct; it only limits damage. The model also may return text and a tool request in the same response.', 'If an option decides completion because the response begins with text or says “done,” reject it. stop_reason is the control signal.', 'loop', 'while (response.stop_reason === "tool_use") {\n  results = runTools(response.content);\n  messages.push({ role: "user", content: results });\n  response = client.messages.create({ messages });\n}'),
    lesson('multi-agent-orchestration', 'Multi-Agent Orchestration', 'A complex task needs research, analysis, and review, but giving every agent the whole job produces duplicated work and unclear ownership.', 'Use a coordinator that decomposes work, selects only needed specialists, passes task-specific context, and synthesizes results. Partition scopes so independent agents can run in parallel.', 'Subagents do not inherit the coordinator’s full context, goals, or other agents’ outputs. More agents increase coordination cost and can make simple tasks worse.', 'Choose hub-and-spoke when the prompt emphasizes specialized, independent work and a final synthesis. Reject a fixed pipeline when the needed specialists depend on the request.', 'hub'),
    lesson('subagent-context-passing', 'Subagent Context Passing', 'A synthesis agent receives findings that look credible but cannot identify where a claim came from or whether two researchers used the same source.', 'Pass self-contained instructions and structured findings that keep content with provenance: source URL or file, location, confidence, and limitations. Give each subagent the exact success criteria it needs.', 'A coordinator cannot assume a subagent sees its system prompt or conversation. Passing raw prose without metadata loses attribution.', 'When the scenario mentions unsourced synthesis, the repair is structured metadata in the handoff, not a stronger prompt asking agents to be careful.', 'hub'),
    lesson('parallel-and-sequential-delegation', 'Parallel and Sequential Delegation', 'Several research tasks have no dependencies, but a coordinator invokes them one at a time and makes users wait for needless round trips.', 'Issue independent subagent calls in the same turn. Use sequential delegation only when a later task requires an earlier result, such as review after implementation.', 'Parallel work needs distinct scope and an integration plan. Parallel agents editing the same artifact can create conflicts.', 'The key question is dependency. Independent means parallel; output-dependent means sequential.', 'hub'),
    lesson('workflow-enforcement', 'Programmatic Enforcement', 'A refund, payment, security action, or compliance step must never proceed without verification, even if a model instruction says it should.', 'Put the rule in code: a pre-execution gate validates prerequisites and blocks or routes the action before the tool runs. Use prompts for low-stakes style and ordering guidance.', 'Prompt compliance is probabilistic. Post-hoc review can detect a violation but cannot prevent an already executed financial or security action.', 'Words such as must never, payment, transfer, identity, or compliance point to deterministic programmatic enforcement.', 'gate'),
    lesson('agent-sdk-hooks', 'Agent SDK Hooks', 'Tool inputs arrive in inconsistent formats, or policy has to be checked at the exact point an agent attempts an action.', 'Use PreToolUse hooks to block, modify, or redirect a call before execution. Use PostToolUse hooks to normalize results before the model reasons over them. Scope hooks to the agent and tool where possible.', 'A hook is not a replacement for architectural design; it is a precise control point. Subagent lifecycle hooks have different capabilities from per-tool hooks.', 'PreToolUse means prevent or modify before the action. PostToolUse means normalize or validate the result after the action.', 'gate'),
    lesson('task-decomposition', 'Task Decomposition', 'A large review asks one agent to inspect many files at once. The output has uneven depth and misses cross-file interactions.', 'Use a multi-pass architecture: local, per-item analysis first; then a dedicated integration pass for dependencies, data flow, and consistency. Use dynamic decomposition when new discoveries change the needed work.', 'A fixed prompt chain is appropriate only when the workflow is known in advance. Splitting tasks too narrowly can create coverage gaps.', 'Attention dilution points to focused per-item passes; cross-cutting concerns point to a separate integration pass.', 'hub'),
    lesson('session-resumption', 'Session Resumption', 'A resumed coding session relies on tool output from before a refactor and starts making claims that conflict with the current repository.', 'Resume a named session only when its history remains useful. For changed code, inject a concise prior summary and re-analyze the changed files before trusting old observations.', 'Resume retains history; it does not refresh old tool results. fork_session creates an independent branch, while --resume continues the same line of work.', 'Stale context calls for targeted re-analysis, not blind continuation or a complete reread of the entire codebase.', 'context')
  ]);

  window.SITE_CONTENT['tools-mcp'] = track('2. Tool Design & MCP Integration — 18%', [
    lesson('tool-interface-design', 'Tool Interface Design', 'An agent chooses the wrong one of two overlapping tools even though both implementations are correct.', 'Improve the tool descriptions and names first. A production description states purpose, inputs, example queries, edge cases or limitations, and explicit boundaries. Split an overly broad tool into narrow interfaces when its jobs differ.', 'Few-shot examples in a system prompt add token cost and do not fix ambiguous tool contracts. A classifier layer is usually over-engineering as the first repair.', 'Misrouting plus overlapping descriptions means improve the interface contract before adding prompt examples or a router.', 'tool'),
    lesson('structured-error-responses', 'Structured Error Responses', 'A lookup fails, but the agent cannot tell whether it should retry, correct its input, ask for access, or tell the user that no record exists.', 'Return an error signal the model can reason about, with category and retryability. Separate transient, validation, business-policy, and permission errors; distinguish a valid empty result from an access failure.', 'Retrying the same request only helps transient errors. A business rule violation requires a different path; a malformed input requires correction.', 'The best answer distinguishes “not found” from “could not reach the source,” and marks recoverable execution failures explicitly.', 'tool'),
    lesson('tool-distribution', 'Tool Distribution and Least Privilege', 'One generalist agent receives eighteen tools and starts choosing irrelevant capabilities, while specialists have permissions they do not need.', 'Give each role a small, task-specific toolset, usually around four or five tools. Use constrained cross-role tools for occasional needs, and parameterize near-duplicate operations with an enum where their contract is genuinely the same.', 'A coordinator hop adds latency; do not route simple specialist work through it solely for centralization. Do not give unrestricted tools when a validated narrow alternative exists.', 'The cue is tool overload or least privilege: reduce the tool surface before writing longer instructions.', 'tool'),
    lesson('tool-choice', 'Tool Choice', 'A workflow needs either a model-selected tool call, any tool call, or one exact tool call depending on the state of the interaction.', 'Use auto when Claude may answer directly or call a tool; use any when it must call some available tool; force a named tool only when the workflow already knows which operation is required.', 'Forcing a specific tool removes model discretion and can cause invalid calls if the request has not been validated.', 'Read “must use a tool” carefully: it is not the same as “must use this named tool.”', 'tool'),
    lesson('mcp-configuration', 'MCP Configuration Scope', 'A team wants shared issue-tracker access while a developer needs a private personal integration and neither should commit credentials.', 'Put shared project configuration in .mcp.json at the repository root and keep personal configuration in the user-level Claude settings. Reference secrets through environment variables rather than committing their values.', 'A project file is shared and version-controlled; a user-level file is not. Scope should follow who needs the configuration.', 'Team-wide and reproducible point to project scope. Personal and credential-specific point to user scope.', 'config', '{\n  "mcpServers": {\n    "issues": { "command": "node", "args": ["server.js"], "env": { "TOKEN": "${ISSUE_TOKEN}" } }\n  }\n}'),
    lesson('mcp-build-vs-use', 'MCP Build-versus-Use Decision', 'A team needs access to a standard service such as GitHub, Jira, or Slack and immediately proposes a custom server.', 'Evaluate existing maintained community integrations first. Build a custom MCP server when the workflow or proprietary system needs capabilities that available integrations cannot provide.', 'A custom server creates ownership for security, uptime, schema quality, and versioning. An existing server still needs a trust and permission review.', 'Standard integration plus no unique workflow is a use-existing-server scenario. Proprietary workflow plus missing capability is a build-custom-server scenario.', 'tool'),
    lesson('built-in-tools', 'Claude Code Built-in Tools', 'An agent loads an entire repository to find one call site, wastes context, and misses a wrapper module that re-exports the target function.', 'Use incremental discovery: Glob finds paths, Grep finds content, Read follows relevant files and imports, Edit makes a unique targeted change, and Bash runs verification. Search direct names, sibling tests, then wrapper or barrel exports.', 'An Edit match that appears more than once is unsafe. Widen the anchor with surrounding context or use an intentional replace-all.', 'For codebase exploration, choose the smallest tool that answers the current question; do not begin by reading everything.', 'tool')
  ]);

  window.SITE_CONTENT['claude-code'] = track('3. Claude Code Configuration & Workflows — 20%', [
    lesson('claude-md-hierarchy', 'CLAUDE.md Hierarchy', 'A repository has rules for all code plus stricter rules for a security-sensitive directory, and the team needs changes to follow both consistently.', 'Use root CLAUDE.md for shared project instructions and path-specific CLAUDE.md files for local rules. Keep instructions concrete: commands, conventions, boundaries, and review expectations.', 'Configuration only guides the model; use code and CI checks for requirements that must be enforced. Conflicting or vague instructions reduce reliability.', 'Shared conventions belong at the repository root; rules that only apply below a path belong next to that path.', 'config'),
    lesson('skills-and-commands', 'Skills and Custom Commands', 'A team repeats a multi-step workflow with the same context, tools, and quality criteria, but every prompt re-explains it inconsistently.', 'Use reusable skills for a scoped way of working and custom commands for named repeatable actions. Store project-shared assets with the repository so teammates receive the same workflow.', 'A command name does not guarantee output quality by itself. The instruction still needs clear scope, inputs, and validation criteria.', 'Repeated named workflow points to a command or skill; one-off work usually needs a direct prompt instead.', 'config'),
    lesson('subagents-in-claude-code', 'Subagents in Claude Code', 'A coding task needs independent reconnaissance, implementation, and review without mixing every intermediate result into one context window.', 'Define specialized agents with explicit purpose, instructions, and tool restrictions. Give the coordinator permission to invoke the Agent or Task tool and pass the context each specialist needs.', 'Subagents are isolated by design. They do not automatically share the parent conversation or one another’s discoveries.', 'If the answer assumes inherited context, it is wrong. The coordinator must explicitly pass requirements and preserve important findings.', 'hub'),
    lesson('plan-mode', 'Plan Mode', 'A request changes a cross-cutting design with unclear dependencies and risk, yet implementation starts before the repository has been mapped.', 'Use plan mode to explore, trace dependencies, evaluate alternatives, and present an implementation strategy before edits. Use direct execution for a narrow, understood change with clear scope.', 'Planning is not a substitute for execution, and direct execution is not reckless when the task is truly local and well specified.', 'Ambiguous architecture and wide impact point to plan mode. Clear single-file change points to direct execution.', 'config'),
    lesson('iterative-refinement', 'Iterative Refinement', 'A model repeatedly produces inconsistent formatting or applies a requested transformation differently across files.', 'Start with two to four concrete input/output examples that demonstrate the desired pattern and its reasoning. Then use targeted feedback tied to observed output, rather than adding generic detail repeatedly.', 'Examples are not the first fix for tool routing; they are strong for output-shape and judgment consistency. Do not use examples that teach a superficial pattern without explaining the decision.', 'Inconsistent transformation or judgment calls point to concrete before/after examples with rationale.', 'prompt'),
    lesson('non-interactive-and-ci', 'Non-Interactive Mode and CI', 'A CI job needs Claude to review a pull request, follow repository standards, emit a usable result, and exit without human input.', 'Use print mode for non-interactive invocation, provide repository guidance through CLAUDE.md, set a deliberate permission mode, and make validation commands part of the workflow. Separate generation and review sessions when independence reduces self-justification bias.', 'CI should not grant broad write permissions by default. A passing text response is not evidence that generated code builds or tests.', 'Automation, print mode, and reproducibility point to non-interactive invocation plus explicit repo context and verification.', 'config'),
    lesson('permissions-and-safety', 'Permission Modes', 'A workflow needs different levels of tool access for interactive development, CI, and sensitive operations.', 'Select a permission mode that matches the environment and risk, keeping human approval for consequential actions. Restrict agent and tool capabilities by default, then expand only where the workflow requires it.', 'A bypass setting can remove useful safety checks; it is not a general performance optimization.', 'When a question mentions unrestricted execution or sensitive side effects, choose the least permissive mode that still completes the task.', 'gate')
  ]);

  window.SITE_CONTENT.prompting = track('4. Prompt Engineering & Structured Output — 20%', [
    lesson('few-shot-prompting', 'Few-Shot Prompting', 'An extraction or review task has a clear desired format but produces inconsistent fields and inconsistent treatment of edge cases.', 'Provide two to four targeted examples that cover typical and edge cases, including short reasoning for why each output is correct. Examples teach the decision boundary as well as the shape.', 'Too many examples waste context and can obscure the instruction. Few-shot examples do not cure fabricated data when the output needs schema-level validation.', 'Inconsistent format or judgments points to few-shot examples. Missing or fabricated fields points to schemas and validation.', 'prompt'),
    lesson('structured-output', 'Structured Output', 'Downstream code needs fields it can parse, validate, store, and compare, but prose answers vary in order and omit required information.', 'Define a schema with typed fields, required properties, bounded enumerations, and descriptions. Let the consuming system validate it before applying any action.', 'A schema constrains shape, not factual correctness. It cannot make an ungrounded model answer true.', 'If a workflow needs machine handling, use structured output instead of requesting “please return JSON” in prose alone.', 'prompt'),
    lesson('validation-and-retry', 'Validation and Retry', 'An extraction must reconcile line-item amounts with a stated total; a valid-looking answer may still contain a discrepancy.', 'Validate deterministic invariants after generation. Return a targeted error that identifies the failed field or calculation, then retry only the affected record with the corrective context.', 'Blindly retrying identical prompts can repeat the same mistake. Not every error is retriable; policy and permission failures need a different route.', 'A numerical or schema discrepancy points to validate-then-retry. The strongest answer names the invariant and the recovery path.', 'prompt'),
    lesson('batch-processing', 'Batch Processing', 'A large document set is too large for one context window and needs consistent extraction plus a way to recover from individual failures.', 'Chunk by a stable unit, process items independently, preserve item identity and provenance, validate each result, and resubmit only failures. Aggregate only after the per-item contract is satisfied.', 'A single giant prompt risks attention dilution and makes it hard to locate the source of an error. Chunk boundaries can lose cross-item dependencies.', 'Large collections point to per-item processing and targeted resubmission; cross-file questions require a later integration pass.', 'prompt'),
    lesson('multi-pass-review', 'Multi-Pass Review', 'A repository review catches local style problems but misses inconsistent API assumptions and data flow across modules.', 'Separate local file analysis from a second integration pass that receives structured local findings. The second pass checks cross-cutting contracts, dependencies, and system-level behavior.', 'A broad first pass can weaken local depth; the integration pass needs findings with paths and evidence, not an untraceable prose summary.', 'Local defects and cross-file defects are different tasks. The exam answer should preserve both passes.', 'hub'),
    lesson('evaluation-design', 'Evaluation Design', 'A team believes a prompt is ready because a few manually chosen examples look good, but production inputs are diverse and failure costs differ.', 'Create representative evaluation cases, define observable success criteria, classify failures, and compare prompt or architecture changes against the same set. Include difficult edge cases and measure the errors that matter to users.', 'A high aggregate score can hide a severe safety or extraction failure. Evaluation data must match the real decision distribution.', '“Looks good on examples” is not an evaluation plan. Look for representative cases, explicit criteria, and error analysis.', 'prompt')
  ]);

  window.SITE_CONTENT.reliability = track('5. Context Management & Reliability — 15%', [
    lesson('context-window-management', 'Context Window Management', 'An agent receives every document, tool result, and previous discussion until relevant instructions are drowned out by stale detail.', 'Select only relevant material, summarize completed work into durable facts, keep source metadata, and retrieve additional detail only when needed. Compact or restart with a structured handoff when context becomes degraded.', 'Summaries can omit important caveats. A compacted context should retain requirements, decisions, evidence, open questions, and provenance.', 'Context overload is solved by selection and summarization, not by blindly increasing prompt length.', 'context'),
    lesson('session-state', 'Session State and Resumption', 'A long-running task pauses after edits, then resumes with an old analysis that no longer matches the files on disk.', 'Name resumable sessions when continuity helps, but re-read changed artifacts and run targeted re-analysis before relying on cached observations. Start fresh with a structured summary when the old conversation has become noisy.', 'Continuing a session preserves its reasoning history; it does not make that history current. Forking creates a divergent branch rather than a continuation.', 'Stale tool results point to re-verification of changed files, not to trusting the resume mechanism as source of truth.', 'context'),
    lesson('provenance-and-attribution', 'Provenance and Attribution', 'A final recommendation is persuasive but reviewers cannot trace its claims to a source, page, tool result, or confidence level.', 'Carry provenance with each fact through retrieval, subagent handoffs, synthesis, and final output. Use structured records that retain source, location, timestamp, and uncertainty where relevant.', 'Citation alone does not prove a claim is supported; the cited material must directly bear on the conclusion. Attribution is lost when content is copied without metadata.', 'When the scenario mentions unsourced claims, add metadata to the information flow rather than asking the writer to cite more carefully.', 'context'),
    lesson('escalation-and-human-review', 'Escalation and Human Review', 'An agent faces an ambiguous request, low-confidence conclusion, or action with an irreversible business consequence.', 'Define escalation thresholds and route the case with the evidence, uncertainty, and recommended next action. Require human approval for high-impact decisions even if the agent can formulate a recommendation.', 'A confidence score by itself is not a policy. Thresholds need a consequence-aware rule and a route for the person who can decide.', 'Ambiguity, high impact, or missing authority point to escalation. The correct design explains what information the reviewer receives.', 'gate'),
    lesson('error-propagation', 'Error Propagation and Recovery', 'A subagent encounters a transient data-source failure while researching one part of a larger task.', 'Retry locally when the error is transient and safe to retry. If it remains unresolved, propagate a structured failure with scope, attempts, partial results, and next action so the coordinator can decide whether to continue or escalate.', 'Do not silently convert a failure into an empty result. Do not escalate every recoverable timeout to the coordinator.', 'Recover locally when possible; propagate only what cannot be resolved, with enough context for the coordinator to reason correctly.', 'context')
  ]);

  window.SITE_CONTENT['exam-drills'] = track('6. Original Exam Decision Drills', [
    lesson('exam-blueprint', 'Exam Blueprint and Study Plan', 'You need to allocate preparation time across a 60-question, 120-minute, scenario-based exam instead of studying every topic equally.', 'Weight your time toward Agentic Architecture and Orchestration (27%), then Claude Code and Prompt Engineering (20% each), Tool Design and MCP (18%), and Context Management and Reliability (15%). Practice choosing the most specific design that satisfies the scenario constraint, then explain why the nearest alternative fails.', 'The published format and policies can change. Recheck the official certification page and exam guide before booking the exam; this lesson reflects the current blueprint used to structure this course.', 'A scenario question rewards architectural judgment, not memorized definitions. Identify the required guarantee first: deterministic control, isolation, provenance, recovery, or output validity.', 'drill', '60 questions · 120 minutes\nPassing score: 720 / 1,000\nQuestion types: multiple choice and multiple response'),
    lesson('drill-deterministic-control', 'Deterministic Control Decisions', 'An assistant may issue refunds only after identity verification and manager approval above a threshold. The option list includes a strong system prompt, a post-processing checker, and a pre-execution hook.', 'Choose the pre-execution programmatic gate. It prevents the prohibited tool call and can route the case before any side effect occurs.', 'A prompt may work often but has a non-zero failure rate. A post-processing checker sees the action after the risk has occurred.', 'Trigger words: must never, payment, threshold, approval, compliance. Translate them to an enforced gate.', 'drill'),
    lesson('drill-tool-misrouting', 'Tool Misrouting Decisions', 'An agent confuses get_customer and search_customers because both descriptions say “find customer information.” The options add ten prompt examples, build a router, rename and clarify tools, or increase context.', 'Choose narrow names and descriptions with purpose, inputs, examples, limitations, and boundaries. If operations are genuinely distinct, split the interface.', 'Extra examples can mask a bad interface and consume tokens. A classifier is a later architectural option, not the first repair for ambiguous contracts.', 'Trigger words: overlapping tools, wrong tool, ambiguous description. The first repair is tool interface design.', 'drill'),
    lesson('drill-context-isolation', 'Subagent Context Decisions', 'A coordinator asks one subagent to research policy, another to calculate impact, and a third to synthesize. The synthesis contains claims with no traceable evidence.', 'Choose a structured handoff that includes each finding plus source, location, confidence, and limitations. Give the synthesis agent the relevant metadata explicitly.', 'Subagents do not share memory by default. Asking them to “use the prior context” does not provide it.', 'Trigger words: isolated agents, source-less claims, handoff. The answer must carry provenance across boundaries.', 'drill'),
    lesson('drill-stale-session', 'Stale Session Decisions', 'A named Claude Code session resumes after a refactor. Its earlier tool output names functions that were removed, and its current advice conflicts with the changed files.', 'Choose targeted re-analysis of changed files, optionally from a fresh session seeded by a concise handoff summary. Treat current reads and tests as authoritative.', 'Blind resume preserves stale observations. Re-reading the entire repository is unnecessary if the changed scope is known.', 'Trigger words: resumed session, old results, refactor, contradictory advice. Re-verify the changed state.', 'drill'),
    lesson('drill-output-reliability', 'Structured Output Decisions', 'A document pipeline occasionally produces a valid JSON object whose item amounts do not equal the invoice total. The options request more detailed prose, add examples, validate the invariant and retry, or accept the result because the schema passed.', 'Choose deterministic validation of the total and a targeted retry that exposes the discrepancy. Preserve the failed item identity for diagnosis and selective resubmission.', 'A schema validates shape, not arithmetic truth. More prose does not establish a reliable feedback loop.', 'Trigger words: valid format but inconsistent values. Use an invariant, a specific failure signal, and targeted recovery.', 'drill')
  ]);

  window.SITE_CONTENT['practice-sets'] = track('7. Original Practice Question Sets', [
    questionSet('architecture-practice', 'Architecture Practice Questions', [
      { prompt: 'An agent should continue after it executes a requested tool. Which signal should control the next step?', options: ['The first content block is text', 'The response stop reason is tool_use', 'The agent says it needs more information', 'The iteration count is below ten'], answer: 'B', reason: 'The stop reason is the authoritative execution signal. Text can coexist with tool-use blocks, and a cap is only a safety fallback.' },
      { prompt: 'Three independent source reviews must be completed before a final report. Which orchestration minimizes avoidable latency?', options: ['Run all specialists in parallel and synthesize afterward', 'Run each specialist in a fixed sequence', 'Ask one generalist to inspect all sources', 'Require the user to choose the review order'], answer: 'A', reason: 'The work is independent, so parallel specialists reduce round trips. The coordinator can integrate their structured findings afterward.' },
      { prompt: 'A discount above a policy threshold must never be applied without manager approval. Which control is required?', options: ['A stronger system prompt', 'A post-processing warning', 'A PreToolUse gate that blocks or routes the call', 'A few-shot example of a denied discount'], answer: 'C', reason: 'The scenario requires prevention before a consequential action. A pre-execution programmatic gate provides that deterministic guarantee.' },
      { prompt: 'A cross-repository review misses interactions between files after agents analyze each file separately. What should be added?', options: ['More tools per local agent', 'A cross-file integration pass', 'An arbitrary larger context cap', 'A second copy of every local prompt'], answer: 'B', reason: 'Local passes protect depth; an integration pass is the dedicated place to analyze contracts and data flow across files.' },
      { prompt: 'A synthesis agent cannot support its claims because research findings lost their source locations. What is the first repair?', options: ['Ask it to cite more carefully', 'Pass content together with structured provenance metadata', 'Use a larger model', 'Repeat the same research prompts'], answer: 'B', reason: 'Attribution is an information-flow problem. The coordinator must preserve source and location in the handoff.' }
    ]),
    questionSet('tools-practice', 'Tools and MCP Practice Questions', [
      { prompt: 'Two tools have overlapping descriptions and are frequently confused. What is the best initial change?', options: ['Add many few-shot tool examples to the prompt', 'Build a routing classifier', 'Clarify names and descriptions with boundaries and examples', 'Give the agent more tools'], answer: 'C', reason: 'Tool selection starts with the interface. Clear purpose and boundaries are simpler and more reliable than a new routing layer.' },
      { prompt: 'A tool call receives an invalid date format. Should the agent retry the identical request?', options: ['Yes, all errors are transient', 'No; return a validation error so the agent can correct input', 'Yes; set a higher timeout', 'No; treat it as an empty result'], answer: 'B', reason: 'A malformed input needs correction, not an identical retry. Empty result means the query succeeded and found nothing.' },
      { prompt: 'A team needs a shared GitHub integration with secrets kept out of source control. Where should configuration and credentials go?', options: ['Project .mcp.json with literal tokens', 'Project .mcp.json with environment-variable references', 'Each developer’s personal settings only', 'A CLAUDE.md file containing secrets'], answer: 'B', reason: 'Project configuration is shared and versioned; environment variables keep credentials out of the repository.' },
      { prompt: 'A specialist must always make one available tool call but may choose which suitable one. Which tool-choice mode fits?', options: ['auto', 'any', 'forced selection of a named tool', 'no tool choice parameter'], answer: 'B', reason: 'any requires a tool call while leaving tool selection to the model. Forced selection fixes the exact tool.' },
      { prompt: 'A standard Jira integration exists but an internal workflow has no equivalent capability. What is the appropriate design?', options: ['Build every integration from scratch', 'Use the community Jira server and build custom capability only for the internal gap', 'Avoid MCP entirely', 'Put the internal workflow in a system prompt'], answer: 'B', reason: 'Reuse maintained standard integrations and build custom MCP only where a specific missing, proprietary capability justifies it.' }
    ]),
    questionSet('claude-code-practice', 'Claude Code Practice Questions', [
      { prompt: 'Rules apply to all code, while stricter rules apply only under payments/. Where should they live?', options: ['Only in one root CLAUDE.md', 'Only in a personal config file', 'Root CLAUDE.md plus a path-specific payments/CLAUDE.md', 'A shell alias'], answer: 'C', reason: 'Shared rules belong at the root and scoped rules belong with the directory they govern.' },
      { prompt: 'A change spans unfamiliar modules and has unclear dependency effects. Which workflow is appropriate first?', options: ['Direct execution', 'Plan mode', 'Bypass permissions', 'Print mode'], answer: 'B', reason: 'Plan mode explores the codebase, dependencies, and options before edits when scope and impact are unclear.' },
      { prompt: 'A CI workflow needs Claude to run a review and exit. What configuration is essential?', options: ['Interactive mode and manual approval', 'Print mode with repository guidance and explicit validation', 'A larger terminal window', 'A user-level MCP configuration committed to Git'], answer: 'B', reason: 'Non-interactive print mode makes the process automatable; CLAUDE.md and validation provide reproducible standards.' },
      { prompt: 'A transformation is inconsistently applied despite prose instructions. Which refinement is most useful?', options: ['Two to four concrete before/after examples with rationale', 'More adjectives in the instruction', 'An arbitrary confidence threshold', 'A fixed iteration cap'], answer: 'A', reason: 'Examples establish both output form and decision boundaries, which helps the model generalize the transformation.' },
      { prompt: 'A subagent needs product requirements from its coordinator. What can it assume?', options: ['It inherits the entire parent conversation', 'It can read every other subagent result', 'Only the context explicitly included in its prompt', 'It receives shared memory automatically'], answer: 'C', reason: 'Subagent context is isolated. The coordinator must pass all required instructions and evidence.' }
    ]),
    questionSet('prompting-practice', 'Prompting and Output Practice Questions', [
      { prompt: 'A pipeline needs machine-readable fields with required values and enumerated statuses. Which design is needed?', options: ['Ask politely for JSON', 'Define structured output with a schema', 'Add a longer chain of thought request', 'Use a text-only response'], answer: 'B', reason: 'A schema supplies typed, required, and bounded output constraints that downstream systems can validate.' },
      { prompt: 'Extracted line items are valid JSON but do not equal the stated invoice total. What should happen?', options: ['Accept the schema-valid result', 'Validate the invariant and send a targeted corrective retry', 'Add more style instructions', 'Retry every document without feedback'], answer: 'B', reason: 'Shape validation does not establish arithmetic consistency. An invariant and specific feedback create a recovery loop.' },
      { prompt: 'A large corpus needs consistent extraction but each failed item must be diagnosable. Which design fits?', options: ['One prompt containing the entire corpus', 'Independent chunk processing with identity, validation, and targeted resubmission', 'Only a summary of the corpus', 'A fixed sequential prompt with no validation'], answer: 'B', reason: 'Per-item work limits context and localizes failures; a later integration pass can handle cross-item questions.' },
      { prompt: 'A review is well formatted but sometimes invents an unsupported value. What complements few-shot examples?', options: ['An output schema and validation', 'More examples only', 'A higher iteration cap', 'A generic tool router'], answer: 'A', reason: 'Examples improve consistency; schemas and validation enforce expected fields and catch invalid outputs.' },
      { prompt: 'A team claims a prompt is production-ready after three handpicked demos. What is missing?', options: ['A representative evaluation set with explicit success criteria', 'A second identical prompt', 'More tools', 'A longer system message'], answer: 'A', reason: 'Reliable evaluation reflects real input distribution, edge cases, and the errors that matter to users.' }
    ]),
    questionSet('reliability-practice', 'Reliability Practice Questions', [
      { prompt: 'A resumed session references functions removed by a recent refactor. What is the correct next step?', options: ['Trust the resumed history', 'Re-analyze changed files and verify current state', 'Start a new session with no context', 'Read every file in the repository'], answer: 'B', reason: 'Resumption preserves history, not freshness. Targeted verification restores the authoritative current state.' },
      { prompt: 'A tool times out while a subagent researches one source. What should the subagent do first?', options: ['Return an empty result', 'Retry locally if the failure is transient and safe to retry', 'Escalate immediately without context', 'Invent an answer from prior knowledge'], answer: 'B', reason: 'Recoverable transient errors should be handled locally. Unresolved failures are then propagated with attempts and partial results.' },
      { prompt: 'An agent is unsure whether a high-value action is authorized. What should the system do?', options: ['Proceed if confidence is above 50%', 'Escalate with evidence, uncertainty, and a recommended action', 'Ask the model to be more confident', 'Silently skip the action'], answer: 'B', reason: 'High-impact ambiguity requires a human decision path with enough context for review.' },
      { prompt: 'A final answer must let reviewers trace each important claim. What must survive retrieval and synthesis?', options: ['Only concise summaries', 'Source, location, timestamp or freshness, and uncertainty metadata', 'The original system prompt', 'The agent’s hidden reasoning'], answer: 'B', reason: 'Provenance must travel with the fact through every handoff so claims can be checked.' },
      { prompt: 'A conversation has accumulated irrelevant tool output and the model misses current requirements. What is the best response?', options: ['Add all remaining documents too', 'Select relevant context and compact into a structured handoff', 'Increase arbitrary iteration count', 'Repeat the same prompt verbatim'], answer: 'B', reason: 'Context quality comes from selection and durable summaries, not from retaining every historical detail.' }
    ])
  ]);

  window.SITE_CONTENT.implementation = track('8. Implementation Patterns', [
    lesson('implement-agent-loop', 'Client Tool-Use Loop', 'A service has a client-executed database tool. It gets the first Claude response and returns it immediately, so tool requests never run and the agent appears to stop randomly.', 'Persist the full conversation. On each response, inspect stop_reason. When it is tool_use, execute every tool_use block, append the entire assistant response, append one user message containing matching tool_result blocks, and make the next Messages request. Treat an iteration limit as a circuit breaker, not as the normal completion rule.', 'Do not append only a text summary of the assistant response: tool_use IDs are the correlation keys for tool_result. A non-tool stop reason needs its own handling; max_tokens and refusal are not successful end_turn responses.', 'The subtle implementation detail is message ordering: assistant tool_use response first, then a user message with tool_result blocks keyed by tool_use_id.', 'loop', 'let response = await client.messages.create({ model, max_tokens, tools, messages });\nfor (let turn = 0; response.stop_reason === "tool_use"; turn++) {\n  if (turn >= 8) throw new Error("tool-loop budget exhausted");\n  messages.push({ role: "assistant", content: response.content });\n  const results = await Promise.all(response.content\n    .filter(block => block.type === "tool_use")\n    .map(async block => ({\n      type: "tool_result", tool_use_id: block.id,\n      content: await executeTool(block.name, block.input)\n    })));\n  messages.push({ role: "user", content: results });\n  response = await client.messages.create({ model, max_tokens, tools, messages });\n}'),
    lesson('implement-tool-contract', 'Tool Contract and Error Envelope', 'A tool returns a plain string for a missing record, invalid input, access denial, and upstream timeout. The model cannot select a safe recovery path.', 'Return a small, stable envelope. Keep successful domain data separate from errors; expose a machine-readable code, whether retry is safe, and an operator-safe message. Validate arguments before entering the dependency, and never encode a permission failure as an empty successful lookup.', 'Do not leak stack traces, tokens, or raw upstream responses into model context. Retry only errors explicitly classified as transient, with a bounded backoff and an idempotency plan for side effects.', 'The important nuance is that “not found” is a successful query with zero data, while “forbidden” and “timeout” are different control paths.', 'tool', 'type ToolResult<T> =\n  | { ok: true; data: T; provenance: { source: string; retrievedAt: string } }\n  | { ok: false; error: { code: "VALIDATION" | "FORBIDDEN" | "NOT_FOUND" | "TRANSIENT"; retryable: boolean; message: string } };\n\nfunction missingCustomer(id: string): ToolResult<never> {\n  return { ok: false, error: { code: "NOT_FOUND", retryable: false, message: `No customer exists for ${id}.` } };\n}'),
    lesson('implement-claude-md-layout', 'Repository Instruction Layout', 'A monorepo uses one large CLAUDE.md containing generic rules, package-specific test commands, and personal environment paths. Agents apply irrelevant rules and teammates inherit local assumptions.', 'Keep durable team rules and the default verification command in root CLAUDE.md. Place narrow rules next to the governed subtree, and use imports for maintained supporting documents. Keep personal paths and credentials out of committed instructions; make every requirement observable where possible.', 'CLAUDE.md guides behavior; it does not replace linting, type checking, tests, branch protection, or a review gate. Instructions that conflict between levels should be removed or made explicitly scoped.', 'Implementation quality comes from a small instruction surface with executable checks, not from turning CLAUDE.md into a complete design document.', 'config', '# CLAUDE.md\n## Verification\n- Run: pnpm test && pnpm lint\n- Do not edit generated files under dist/\n\n## Service boundary\n- @services/payments/CLAUDE.md\n\n# services/payments/CLAUDE.md\n- Changes to settlement logic require payment-specific tests.\n- Never log card or bank identifiers.\n- Run: pnpm --filter payments test'),
    lesson('implement-mcp-project-config', 'Project MCP Configuration', 'A team commits a shared MCP configuration with a literal bearer token. It works on one laptop, leaks on review, and cannot be rotated without rewriting history.', 'Commit only the server identity and environment-variable references in .mcp.json. Use project scope for a reproducible team integration, local scope for an individual experiment or credential-bound setup, and user scope for a personal utility used across repositories. Record the expected permissions and verification command in project documentation.', 'Environment-variable expansion is not a secret manager. Inject values through the developer environment or CI secret store, and restrict server tokens to the minimum required scope.', 'The nuance is scope separation: share the integration recipe, not the credential. Project-scope servers also require approval before use.', 'config', '{\n  "mcpServers": {\n    "issue-tracker": {\n      "type": "http",\n      "url": "${ISSUE_MCP_URL:-https://mcp.example.com}",\n      "headers": { "Authorization": "Bearer ${ISSUE_MCP_TOKEN}" }\n    }\n  }\n}\n\n# Verify after configuration\nclaude mcp get issue-tracker'),
    lesson('implement-pre-execution-gate', 'Pre-Execution Policy Gate', 'An agent proposes a production refund. The prompt asks it to seek approval, but the actual tool can still be invoked with a valid refund payload.', 'Put the authorization decision in the tool executor or a PreToolUse control point. Verify identity, approval evidence, threshold, idempotency key, and allowed account before making the irreversible call. Return a structured denial or escalation record that lets the model explain the next human action without retrying the side effect.', 'A post-tool audit may detect an unauthorized refund but cannot prevent it. The model should not be responsible for interpreting a policy threshold that software can evaluate deterministically.', 'The gate owns side-effect policy; the prompt owns explanation and user interaction.', 'gate', 'function authorizeRefund(input: RefundInput, actor: Actor): GateResult {\n  if (!actor.scopes.includes("refund:write")) return deny("FORBIDDEN");\n  if (input.amountCents > 50_000 && !input.managerApprovalId) return escalate("MANAGER_APPROVAL_REQUIRED");\n  if (!input.idempotencyKey) return deny("IDEMPOTENCY_KEY_REQUIRED");\n  return allow();\n}\n\nconst decision = authorizeRefund(input, actor);\nif (!decision.allowed) return asToolResult(decision);\nreturn payments.refund(input);'),
    lesson('implement-structured-output', 'Structured Output and Semantic Validation', 'A document extractor returns parseable JSON for every invoice, but some results have duplicate line numbers or a line-item sum that differs from the invoice total.', 'Use output_config.format with a JSON Schema for the response contract, then run deterministic semantic validation in application code. On a recoverable discrepancy, retry the individual item with the failed invariant and relevant source slice. Preserve the raw model response, validated data, and validation result under the record ID.', 'Schema conformance is not a factual or arithmetic guarantee. Structured output can still be interrupted by a refusal or token limit, so inspect stop_reason before treating text as a usable document.', 'A production implementation has two layers: shape constrained by JSON Schema and truth-like invariants checked by deterministic code.', 'prompt', 'const response = await client.messages.create({\n  model, max_tokens: 1200, messages,\n  output_config: { format: {\n    type: "json_schema",\n    schema: { type: "object", properties: { total: { type: "number" }, items: { type: "array" } }, required: ["total", "items"], additionalProperties: false }\n  }}\n});\nif (response.stop_reason !== "end_turn") throw new Error(`unexpected stop: ${response.stop_reason}`);\nconst invoice = JSON.parse(response.content.find(b => b.type === "text").text);\nif (sum(invoice.items) !== invoice.total) retryRecord({ reason: "LINE_TOTAL_MISMATCH" });'),
    lesson('implement-subagent-handoff', 'Subagent Handoff Contract', 'A coordinator launches research, implementation, and review agents. The review agent sees only a prose conclusion, cannot reproduce the changes, and accidentally reviews an obsolete revision.', 'Define an explicit handoff payload. Include task and acceptance criteria, repository revision, files or artifact references, decisions with rationale, evidence with locations, open risks, and exact next action. Keep payloads compact by linking to artifacts instead of embedding full logs.', 'Do not assume isolated agents share a parent transcript. Do not let a summary overwrite uncertainty; mark what was not checked and whether the evidence is current for the stated revision.', 'The implementation detail that prevents stale review is binding every claim and changed-file list to a revision or timestamp.', 'hub', 'type Handoff = {\n  task: string; revision: string; acceptanceCriteria: string[];\n  changedFiles: string[];\n  decisions: Array<{ decision: string; rationale: string }>;\n  evidence: Array<{ claim: string; source: string; location: string }>;\n  openRisks: string[]; nextAction: string;\n};\n\n// Review agent rejects the handoff when revision !== currentGitHead().'),
    lesson('implement-noninteractive-ci', 'Non-Interactive Review in CI', 'A workflow invokes Claude automatically with broad capabilities, treats a natural-language “looks good” as a passing signal, and has no deterministic artifact for later review.', 'Run a narrow, read-oriented review job with explicit allowed tools, repository instructions, pinned validation commands, and machine-readable output captured as a build artifact. Keep write-capable implementation jobs separate and gated by protected branches or a human approval step. Fail the job when required checks or output parsing fails.', 'Never put long-lived credentials in workflow text or grant a review job deployment permissions. A model review complements, rather than replaces, deterministic tests and static analysis.', 'CI nuance: separate the agent result from the delivery decision. The pipeline should consume structured findings and still run its ordinary checks.', 'config', 'name: AI review\non: [pull_request]\njobs:\n  review:\n    runs-on: ubuntu-latest\n    permissions: { contents: read, pull-requests: read }\n    steps:\n      - uses: actions/checkout@v4\n      - run: pnpm test && pnpm lint\n      - run: >-\n          claude -p "Review this diff. Return findings with file and line."\n          --allowedTools "Read,Grep,Glob"\n          --output-format json > claude-review.json\n      - uses: actions/upload-artifact@v4\n        with: { name: claude-review, path: claude-review.json }'),
    lesson('implement-evaluation-harness', 'Evaluation Harness and Release Gate', 'A prompt change looks better on a few handpicked examples, but no one can quantify whether it improved tool routing, reduced retries, or introduced regressions on sensitive inputs.', 'Version an evaluation set with expected outcomes, run the same cases before and after a change, and record per-case evidence: selected tool, schema validity, invariant result, latency, cost, and reviewer disposition. Set release gates around the failures that matter, not a single undifferentiated score.', 'Do not tune on the same cases used as your only release test. Separate development, regression, and holdout sets, and review high-impact failures even if the aggregate metric improves.', 'The operational nuance is comparability: a prompt or tool change is meaningful only against a fixed, versioned evaluation contract.', 'drill', 'const cases = loadJsonl("evals/refund-routing.v1.jsonl");\nconst report = await Promise.all(cases.map(async c => {\n  const run = await invokeAgent(c.input);\n  return { id: c.id, tool: run.toolName, schemaOk: validate(run.output),\n    expectedTool: c.expectedTool, pass: run.toolName === c.expectedTool };\n}));\nif (report.some(r => !r.pass)) process.exitCode = 1;\nwriteFileSync("artifacts/eval-report.json", JSON.stringify(report, null, 2));')
  ]);
})();
